export {
  type LengthUnit,
  type ObservationVector,
  type Triangle,
  type ObservedFrame,
  type SurfaceObservation,
  type DimensionObservation,
  type PlaneObservation,
  type CylinderObservation,
  type AnalyticSurfaceObservation,
  type LineObservation,
  type CircleObservation,
  type AnalyticCurveObservation,
  type TopologyObservation,
  type TopologyEdgeObservation,
  type TopologyFaceObservation,
  type AnalyticEvidence,
  type ReconstructionTarget,
  type ReferenceSpatialNode,
  type ReferenceProductNode,
  type ReferenceSceneNode,
  type ReferenceScene,
  type ReferenceRepetitionObservation,
} from './contracts.js';
export {
  referenceHarnessError,
  type ReferenceHarnessErrorCode,
  type ReferenceHarnessErrorContext,
  type ReferenceHarnessError,
} from './errors.js';
export {
  loadReference,
  inspectReference,
  type ReferenceManifestMapping,
  type ReferenceManifest,
  type LoadReferenceRequest,
  type LoadedReference,
  type ReferenceHarnessResult,
  type ReferenceInspection,
  type ReferenceInspectionProduct,
} from './referenceHarness.js';
export { scoreCandidate, type CandidateScore, type EnvelopeDeltas } from './scoring.js';
export {
  compareReconstructionCase,
  isRigidObservedFrame,
  type CandidateOccurrenceObservation,
  type CompareReconstructionCaseRequest,
  type FidelityGateId,
  type FidelityGateEvidence,
  type ComponentComparisonCase,
  type ComparisonCaseErrorStage,
  type ComparisonCaseErrorCode,
  type ComparisonCaseError,
  type ComparisonCaseResult,
} from './comparisonCase.js';
